# Generated by Django 4.0.3 on 2022-03-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
        ('supers_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_Type',
            new_name='SuperType',
        ),
    ]
